"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, Download, LockKeyhole, RotateCcw, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { QrCodeSvg } from "@/components/shared/qr-code";
import type { TechnicianReport } from "@/features/reports/types";
import { usePageOrigin } from "@/hooks/use-page-origin";
import { authFetch, downloadAuthenticatedFile } from "@/lib/api/client";
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <Card className="border-0 ring-1 ring-slate-200"><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{children}</CardContent></Card>; }
export function ReportDetailScreen({ id }: { id: string }) {
  const [report, setReport] = useState<TechnicianReport | null>(null); const [comments, setComments] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const origin = usePageOrigin();
  const load = useCallback(async () => { try { const response = await authFetch(`/api/reports/${id}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail ?? "Report could not be loaded."); setReport(payload); } catch (cause) { setError(cause instanceof Error ? cause.message : "Report could not be loaded."); } }, [id]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function review(action: "approve" | "reject" | "revision_requested") { if (action !== "approve" && comments.trim().length < 3) { setError("Add comments explaining the decision."); return; } setSaving(true); setError(""); try { const response = await authFetch(`/api/reports/${id}/review`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, notes: comments.trim() }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail ?? Object.values(payload)[0] ?? "Review failed."); setReport(payload); setComments(""); setMessage(`Report ${action === "approve" ? "approved" : action === "reject" ? "rejected" : "returned for revision"}.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Review failed."); } finally { setSaving(false); } }
  if (!report) return <div className="p-7">{error || "Loading report…"}</div>;
  const publicUrl = origin ? `${origin}/reports/verify/${report.verification_token}` : "";
  return <div className="space-y-5 p-4 sm:p-6 lg:p-7"><div><Link href="/supervisor/reports" className="inline-flex items-center gap-1 text-sm text-sky-700"><ArrowLeft className="size-4" />Reports</Link><h1 className="mt-3 text-3xl font-semibold">{report.report_number}</h1><p className="text-sm text-slate-500">{report.technician_name} · {report.project_site_name}</p></div>{error ? <p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}{message ? <p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p> : null}
    <div className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><div className="space-y-5"><Section title="Submission details"><dl className="grid gap-3 text-sm sm:grid-cols-2">{[["Report number", report.report_number], ["Technician", report.technician_name], ["Project / site", report.project_site_name], ["Test method", report.test_method], ["Test date", report.test_date], ["Equipment", report.equipment_details.map((item) => `${item.equipment_number} — ${item.description}`).join(", ")]].map(([label, value]) => <div key={label} className="border-b pb-2"><dt className="text-slate-500">{label}</dt><dd className="font-medium">{value}</dd></div>)}</dl><p className="mt-4 rounded-lg bg-sky-50 p-3 text-sm">{report.remarks || "No remarks."}</p></Section><Section title="PDF report"><Button type="button" onClick={() => void downloadAuthenticatedFile(`/api/reports/${id}/file`, `${report.report_number}.pdf`)}><Download className="size-4" />Download PDF</Button></Section></div>
    <div className="space-y-5"><Section title="QR verification"><div className="flex gap-4"><div className="flex size-36 items-center justify-center rounded-lg border p-3">{report.status === "approved" && publicUrl ? <QrCodeSvg value={publicUrl} className="size-full" /> : <LockKeyhole className="size-12 text-slate-300" />}</div><div className="text-sm"><p className="font-medium">{report.status === "approved" ? "Public verification active" : "Available after approval"}</p>{report.reviewed_at ? <p className="mt-2 text-slate-500">Reviewed {new Date(report.reviewed_at).toLocaleString()}</p> : null}<p className="mt-2 text-slate-500">{report.review_notes}</p></div></div></Section><Section title="Supervisor decision">{report.status === "submitted" ? <div className="space-y-3"><textarea value={comments} onChange={(event) => setComments(event.target.value)} rows={4} placeholder="Comments are required for rejection or revision" className="w-full rounded-lg border p-3 text-sm" /><div className="grid gap-2"><Button disabled={saving} onClick={() => void review("approve")}><Check className="size-4" />Approve and generate QR</Button><Button disabled={saving} onClick={() => void review("reject")} className="bg-rose-600 hover:bg-rose-700"><X className="size-4" />Reject</Button><Button disabled={saving} onClick={() => void review("revision_requested")} className="bg-amber-500 text-slate-950 hover:bg-amber-400"><RotateCcw className="size-4" />Request revision</Button></div></div> : <p className="text-sm text-slate-600">Decision recorded: <strong>{report.status.replaceAll("_", " ")}</strong></p>}</Section></div></div>
  </div>;
}
