"use client";

import { useCallback, useEffect, useState, type ReactNode } from "react";
import Link from "next/link";
import { AlertTriangle, CheckCircle2, Clock3, Coins, Pencil, Timer, Trash2, Wrench } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { DashboardPanel, DashboardTable } from "@/components/shared/dashboard-widgets";
import type { ApiPage, FaultReport, MaintenanceRequest, MaintenanceSummary, ServiceReport } from "@/features/maintenance/types";
import { authFetch } from "@/lib/api/client";

const faultLabels: Record<string, string> = { electrical_power: "Electrical / power", mechanical: "Mechanical", software_firmware: "Software / firmware", calibration_related: "Calibration related", physical_damage: "Physical damage", accessories_cables: "Accessories / cables", other: "Other" };
const chartColors = ["#0ea5e9", "#10b981", "#fbbf24", "#f43f5e", "#8b5cf6", "#06b6d4", "#94a3b8"];
const pillStyles: Record<string, string> = { open: "bg-sky-50 text-sky-700", in_progress: "bg-violet-50 text-violet-700", completed: "bg-emerald-50 text-emerald-700", resolved: "bg-emerald-50 text-emerald-700", successful: "bg-emerald-50 text-emerald-700", cancelled: "bg-slate-100 text-slate-700", closed: "bg-slate-100 text-slate-700", partial: "bg-amber-50 text-amber-700", failed: "bg-rose-50 text-rose-700", urgent: "bg-rose-50 text-rose-700", high: "bg-orange-50 text-orange-700", normal: "bg-amber-50 text-amber-700", low: "bg-emerald-50 text-emerald-700" };
const emptySummary: MaintenanceSummary = { open_requests: 0, in_repair: 0, completed_30_days: 0, overdue: 0, average_downtime_hours: 0, cost_30_days: 0, average_turnaround_days: 0, first_time_fix_rate: 0, fault_types: [] };

function Pill({ code, label }: { code: string; label: string }) { return <span className={`inline-flex min-w-20 justify-center rounded-md px-2 py-1 text-xs font-medium ${pillStyles[code] ?? "bg-slate-100 text-slate-700"}`}>{label}</span>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)); }
function actions(editHref: string, onDelete: () => void): ReactNode { return <span className="flex gap-1"><Button nativeButton={false} render={<Link href={editHref} />} size="icon-sm" variant="ghost" aria-label="Edit record"><Pencil className="size-4" /></Button><Button type="button" size="icon-sm" variant="ghost" className="text-rose-700 hover:bg-rose-50" onClick={onDelete} aria-label="Delete record"><Trash2 className="size-4" /></Button></span>; }

export function MaintenanceStats() {
  const [requests, setRequests] = useState<MaintenanceRequest[]>([]); const [faults, setFaults] = useState<FaultReport[]>([]); const [services, setServices] = useState<ServiceReport[]>([]); const [summary, setSummary] = useState(emptySummary);
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => {
    setLoading(true);
    try {
      const responses = await Promise.all([authFetch("/api/maintenance/requests?page_size=100"), authFetch("/api/maintenance/fault-reports?page_size=100"), authFetch("/api/maintenance/service-reports?page_size=100"), authFetch("/api/maintenance/summary")]);
      const payloads = await Promise.all(responses.map((response) => response.json().catch(() => ({}))));
      const failed = responses.findIndex((response) => !response.ok); if (failed >= 0) throw new Error((payloads[failed] as { detail?: string }).detail || "Maintenance data could not be loaded.");
      setRequests((payloads[0] as ApiPage<MaintenanceRequest>).results); setFaults((payloads[1] as ApiPage<FaultReport>).results); setServices((payloads[2] as ApiPage<ServiceReport>).results); setSummary(payloads[3] as MaintenanceSummary); setError("");
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Maintenance data could not be loaded."); } finally { setLoading(false); }
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function remove(kind: "requests" | "fault-reports" | "service-reports", id: number, label: string) {
    if (!window.confirm(`Delete ${label}? This cannot be undone.`)) return;
    const response = await authFetch(`/api/maintenance/${kind}/${id}`, { method: "DELETE" });
    if (!response.ok) { const payload = await response.json().catch(() => ({})); setError((payload as { detail?: string }).detail || "The record could not be deleted."); return; }
    await load();
  }
  const faultTypes = summary.fault_types.map((item, index) => ({ name: faultLabels[item.fault_type] ?? item.fault_type, value: item.value, color: chartColors[index % chartColors.length] }));
  const faultTotal = faultTypes.reduce((total, item) => total + item.value, 0);
  const repairStatuses = [{ name: "Open", value: summary.open_requests, color: "#0ea5e9" }, { name: "In repair", value: summary.in_repair, color: "#8b5cf6" }, { name: "Completed", value: summary.completed_30_days, color: "#10b981" }, { name: "Overdue", value: summary.overdue, color: "#f43f5e" }];
  const cards = [{ label: "Open requests", value: summary.open_requests, detail: "Awaiting action", icon: Wrench, color: "bg-sky-500" }, { label: "In repair", value: summary.in_repair, detail: "Active work", icon: CheckCircle2, color: "bg-emerald-500" }, { label: "Completed (30 days)", value: summary.completed_30_days, detail: "Returned to service", icon: Wrench, color: "bg-orange-500" }, { label: "Overdue", value: summary.overdue, detail: "Past target date", icon: AlertTriangle, color: "bg-rose-500" }, { label: "Avg. downtime", value: `${summary.average_downtime_hours}h`, detail: "Last 30 days", icon: Clock3, color: "bg-violet-500" }, { label: "Maintenance cost", value: `$${Number(summary.cost_30_days).toLocaleString()}`, detail: "Last 30 days", icon: Coins, color: "bg-amber-500" }];

  return <div className="space-y-5 p-4 sm:p-6 lg:p-7">
    <div><h1 className="text-2xl font-semibold tracking-tight text-slate-900 sm:text-3xl">Maintenance</h1><p className="mt-1 text-sm text-muted-foreground">Live maintenance requests, repairs, service history, and equipment faults.</p></div>
    {error ? <p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}
    {loading ? <p className="rounded-lg bg-white p-6 text-sm text-slate-500 ring-1 ring-slate-200">Loading maintenance data…</p> : null}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{cards.map(({ label, value, detail, icon: Icon, color }) => <Card key={label} className="justify-center gap-0 border-0 py-4 shadow-none ring-1 ring-slate-200/80"><CardContent className="flex items-center gap-3"><span className={`flex size-12 shrink-0 items-center justify-center rounded-lg text-white ${color}`}><Icon className="size-6" /></span><span className="min-w-0"><strong className="block text-xl font-semibold tabular-nums text-slate-900">{value}</strong><span className="block text-xs font-medium text-slate-700">{label}</span><span className="text-[11px] text-slate-500">{detail}</span></span></CardContent></Card>)}</div>
    <div className="grid items-stretch gap-4 xl:grid-cols-12">
      <DashboardPanel title="Maintenance queue" className="xl:col-span-6"><DashboardTable minWidth="min-w-[900px]" headers={["Request", "Equipment", "Description", "Request date", "Priority", "Status", "Target", "Actions"]} rows={requests.map((item) => [item.request_number, item.equipment_number, item.description, formatDate(item.requested_at), <Pill key="priority" code={item.priority} label={item.priority_name} />, <Pill key="status" code={item.status} label={item.status_name} />, item.target_date ? formatDate(item.target_date) : "—", actions(`/supervisor/maintenance/requests/${item.id}/edit`, () => void remove("requests", item.id, item.request_number))])} /></DashboardPanel>
      <DashboardPanel title="Repair status" className="xl:col-span-3"><ChartContainer config={{ value: { label: "Requests" } }} className="h-72 w-full" initialDimension={{ width: 360, height: 288 }}><BarChart data={repairStatuses} margin={{ top: 20, right: 5, left: -20, bottom: 15 }}><CartesianGrid vertical={false} stroke="#e2e8f0" /><XAxis dataKey="name" tick={{ fontSize: 11 }} interval={0} /><YAxis tick={{ fontSize: 11 }} /><ChartTooltip content={<ChartTooltipContent />} /><Bar dataKey="value" radius={[4, 4, 0, 0]}>{repairStatuses.map((item) => <Cell key={item.name} fill={item.color} />)}</Bar></BarChart></ChartContainer></DashboardPanel>
      <div className="space-y-4 xl:col-span-3"><DashboardPanel title="Requests by fault type"><div className="flex flex-col items-center gap-3"><div className="relative w-52"><ChartContainer config={{ value: { label: "Faults" } }} className="aspect-square w-full" initialDimension={{ width: 208, height: 208 }}><PieChart><Pie data={faultTypes} dataKey="value" nameKey="name" innerRadius={62} outerRadius={94} strokeWidth={0}>{faultTypes.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><ChartTooltip content={<ChartTooltipContent nameKey="name" />} /></PieChart></ChartContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><strong className="text-2xl tabular-nums text-slate-900">{faultTotal}</strong><span className="text-xs text-slate-500">Total</span></div></div><ul className="w-full space-y-1">{faultTypes.map((item) => <li key={item.name} className="flex items-center gap-2 text-xs"><span className="size-2.5 rounded-full" style={{ backgroundColor: item.color }} /><span className="flex-1 text-slate-700">{item.name}</span><span>{item.value}</span></li>)}</ul></div></DashboardPanel><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2"><Card className="border-0 shadow-none ring-1 ring-slate-200/80"><CardContent className="flex items-center gap-3"><Timer className="size-8 text-sky-600" /><div><strong className="text-xl tabular-nums">{summary.average_turnaround_days} days</strong><p className="text-xs text-slate-600">Avg. turnaround</p></div></CardContent></Card><Card className="border-0 shadow-none ring-1 ring-slate-200/80"><CardContent className="flex items-center gap-3"><CheckCircle2 className="size-8 text-sky-600" /><div><strong className="text-xl tabular-nums">{summary.first_time_fix_rate}%</strong><p className="text-xs text-slate-600">First-time fix</p></div></CardContent></Card></div></div>
    </div>
    <div className="grid gap-4 xl:grid-cols-2"><DashboardPanel title="Service history"><DashboardTable minWidth="min-w-[900px]" headers={["Service", "Equipment", "Type", "Date", "Provider", "Cost", "Downtime", "Result", "Actions"]} rows={services.map((item) => [item.service_number, item.equipment_number, item.service_type_name, formatDate(item.service_date), item.provider, `$${Number(item.cost_usd).toLocaleString()}`, `${item.downtime_hours}h`, <Pill key="result" code={item.result} label={item.result_name} />, actions(`/supervisor/maintenance/service-reports/${item.id}/edit`, () => void remove("service-reports", item.id, item.service_number))])} /></DashboardPanel><DashboardPanel title="Fault reports"><DashboardTable minWidth="min-w-[780px]" headers={["Report", "Equipment", "Description", "Reported by", "Date", "Priority", "Status", "Actions"]} rows={faults.map((item) => [item.report_number, item.equipment_number, item.description, item.reported_by_name, formatDate(item.reported_at), <Pill key="priority" code={item.priority} label={item.priority_name} />, <Pill key="status" code={item.status} label={item.status_name} />, actions(`/supervisor/maintenance/fault-reports/${item.id}/edit`, () => void remove("fault-reports", item.id, item.report_number))])} /></DashboardPanel></div>
  </div>;
}
