"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarDays, ClipboardList, MapPin, Pencil, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { QrCodeSvg } from "@/components/shared/qr-code";
import { StatusPill } from "@/components/shared/dashboard-widgets";
import type { Allocation } from "@/features/allocations/types";
import { EquipmentPhoto } from "@/features/equipment/components/equipment-photo";
import { equipmentDetailUrl } from "@/features/equipment/lib/equipment-detail-url";
import { usePageOrigin } from "@/hooks/use-page-origin";
import { authFetch } from "@/lib/api/client";

function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(value)) : "—"; }
function DetailCard({ title, children }: { title: string; children: React.ReactNode }) { return <Card className="border-0 shadow-none ring-1 ring-slate-200/80"><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{children}</CardContent></Card>; }

export function AllocationDetailScreen({ id }: { id: string }) {
  const origin = usePageOrigin(); const [allocation, setAllocation] = useState<Allocation | null>(null); const [error, setError] = useState("");
  useEffect(() => { authFetch(`/api/allocations/${id}`).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "Allocation could not be loaded."); setAllocation(payload); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Allocation could not be loaded.")); }, [id]);
  if (error) return <p className="p-6 text-sm text-rose-700">{error}</p>; if (!allocation) return <p className="p-6 text-sm text-slate-500">Loading allocation…</p>;
  const qrUrl = origin ? equipmentDetailUrl(origin, allocation.equipment_qr_token) : "";
  return <div className="space-y-5 p-4 sm:p-6 lg:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><Link href="/supervisor/allocations" className="mb-3 inline-flex items-center gap-1 text-sm text-sky-700 hover:underline"><ArrowLeft className="size-4" /> Allocation history</Link><div className="flex items-center gap-3"><h1 className="text-2xl font-semibold sm:text-3xl">Allocation #{allocation.id}</h1><StatusPill tone={allocation.status === "active" ? "green" : "amber"}>{allocation.status_name}</StatusPill></div><p className="mt-1 text-sm text-slate-500">Complete equipment custody and issue details.</p></div>{allocation.status === "active" ? <Button nativeButton={false} render={<Link href={`/supervisor/allocations/${allocation.id}/edit`} />}><Pencil className="size-4" /> Edit allocation</Button> : null}</div>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-5"><DetailCard title="Selected equipment"><div className="grid gap-5 md:grid-cols-[220px_1fr]"><div className="flex aspect-[4/3] items-center justify-center overflow-hidden rounded-lg border bg-slate-50"><EquipmentPhoto src={allocation.equipment_photo} alt={allocation.equipment_description} /></div><div><Link href={`/supervisor/equipment/${allocation.equipment}`} className="font-mono text-sm font-semibold text-sky-700 hover:underline">{allocation.equipment_number}</Link><h2 className="mt-1 text-lg font-semibold">{allocation.equipment_description}</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2">{[["Category", allocation.equipment_category], ["Status", allocation.equipment_status], ["Brand", allocation.equipment_brand], ["Model", allocation.equipment_model], ["Serial number", allocation.equipment_serial_number], ["Calibration due", allocation.calibration_due ? formatDate(allocation.calibration_due) : "Not recorded"]].map(([label, value]) => <div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="font-medium">{value}</dd></div>)}</dl></div></div></DetailCard><DetailCard title="Accessories / components"><div className="space-y-2">{allocation.accessories.length ? allocation.accessories.map((item) => <div key={item.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span>{item.description}{item.notes ? ` — ${item.notes}` : ""}</span><span className="font-semibold tabular-nums">× {item.quantity}</span></div>) : <p className="text-sm text-slate-500">No accessories recorded.</p>}</div></DetailCard><DetailCard title="Purpose / remarks"><div className="flex gap-3"><ClipboardList className="mt-0.5 size-4 text-slate-400" /><p className="whitespace-pre-wrap text-sm leading-6">{allocation.purpose}</p></div></DetailCard></div>
      <div className="space-y-5 xl:sticky xl:top-20"><DetailCard title="Equipment QR code"><div className="mx-auto size-52 rounded-lg border bg-white p-3">{qrUrl ? <QrCodeSvg value={qrUrl} className="size-full" /> : null}</div><p className="mt-3 break-all rounded bg-slate-50 p-2 text-xs text-slate-500">{qrUrl}</p></DetailCard><DetailCard title="Allocation details"><dl className="space-y-4">{[["Primary custodian", `${allocation.custodian_number} – ${allocation.custodian_name}`, UserRound], ["Additional technicians", allocation.additional_technician_details.map((item) => item.name).join(", ") || "None", UserRound], ["Project / site", `${allocation.project_site_name} – ${allocation.client_name}`, MapPin], ["Issue date", formatDate(allocation.allocated_at), CalendarDays], ["Expected return", formatDate(allocation.expected_return), CalendarDays]].map(([label, value, Icon]) => { const DetailIcon = Icon as typeof UserRound; return <div key={String(label)} className="flex gap-3 border-b pb-3 last:border-0"><DetailIcon className="mt-0.5 size-4 text-slate-400" /><div><dt className="text-xs text-slate-500">{String(label)}</dt><dd className="text-sm font-medium">{String(value)}</dd></div></div>; })}</dl></DetailCard></div></div>
  </div>;
}
