import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { MapPin, ShieldCheck } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { QrCodeSvg } from "@/components/shared/qr-code";
import type { PublicTechnician } from "@/features/technicians/types";
import { apiEndpoints } from "@/lib/api/endpoints";
import { ApiError, apiRequest } from "@/lib/api/server";
import { EmployeeCardActions } from "./employee-card-actions";

interface PageProps { params: Promise<{ token: string }> }
async function getTechnician(token: string) { try { return await apiRequest<PublicTechnician>(apiEndpoints.publicTechnician(token)); } catch (error) { if (error instanceof ApiError && error.status === 404) notFound(); throw error; } }
export async function generateMetadata({ params }: PageProps): Promise<Metadata> { const technician = await getTechnician((await params).token); return { title: `${technician.name} · Employee card` }; }
function value(value: string | null | undefined) { return value?.trim() || "Not provided"; }
export default async function PublicTechnicianPage({ params }: PageProps) {
  const token = (await params).token; const technician = await getTechnician(token); const backendBase = (process.env.API_BASE_URL ?? "").replace(/\/+$/, "");
  const photoUrl = `${backendBase}/public/technicians/${encodeURIComponent(token)}/photo`; const resumeUrl = `${backendBase}/public/technicians/${encodeURIComponent(token)}/resume`; const publicUrl = `${process.env.NEXT_PUBLIC_APP_URL ?? ""}/${encodeURIComponent(token)}`;
  const fields = [["Technician number", technician.technician_number], ["Discipline", technician.discipline], ["Qualification", value(technician.qualification)], ["Iqama number", value(technician.iqama_no)], ["Contact", value(technician.contact)], ["Email", value(technician.email)], ["Location", value(technician.location)], ["Certification expiry", value(technician.certification_expiry)]];
  return <main className="min-h-screen bg-slate-100 px-4 py-8 sm:px-6 print:bg-white print:p-0"><div className="mx-auto max-w-3xl"><Card className="overflow-hidden border-0 shadow-xl ring-1 ring-slate-200 print:shadow-none print:ring-0"><div className="bg-gradient-to-r from-sky-800 to-sky-600 px-6 py-6 text-white sm:px-8"><div className="flex flex-wrap items-center gap-4"><img src="/logo.avif" alt="GRIPCO" className="h-12 w-auto rounded bg-white object-contain p-1" /><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-sky-100">GRIPCO FTIMS</p><h1 className="text-2xl font-bold leading-tight">Employee identification card</h1></div></div></div><CardContent className="p-6 sm:p-8"><div className="grid gap-6 sm:grid-cols-[140px_minmax(0,1fr)_112px] sm:items-start"><div className="overflow-hidden rounded-xl border-4 border-sky-100 bg-slate-100"><img src={photoUrl} alt={`${technician.name} profile`} className="aspect-[4/5] w-full object-cover" /></div><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-sky-700">Authorized technician</p><h2 className="mt-1 break-words text-3xl font-bold leading-tight tracking-tight text-slate-950">{technician.name}</h2><p className="mt-1 break-all font-mono text-sm text-slate-500">{technician.technician_number}</p><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2">{fields.slice(1).map(([label, item]) => <div key={label} className="min-w-0"><dt className="text-xs text-slate-500">{label}</dt><dd className="break-words font-semibold text-slate-900">{item}</dd></div>)}</dl></div><div className="mx-auto w-28 rounded-lg border bg-white p-2"><QrCodeSvg value={publicUrl} label={`${technician.name} employee card`} className="size-full" /><p className="mt-1 text-center text-[10px] leading-tight text-slate-500">Scan to verify</p></div></div><div className="mt-6 border-t pt-4 text-sm"><p className="font-semibold text-slate-800">Skills</p><p className="mt-1 break-words text-slate-600">{value(technician.skills)}</p></div><EmployeeCardActions photoUrl={photoUrl} /><a href={resumeUrl} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-medium text-sky-700 underline print:hidden">View resume</a></CardContent></Card><p className="mt-4 flex items-center justify-center gap-2 text-center text-xs text-slate-500 print:hidden"><MapPin className="size-3.5" />Scan the QR code to open this card</p></div></main>;
}

