"use client";
import { useEffect, useMemo, useState } from "react";
import { ClipboardList, Search } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { Allocation, AllocationPage } from "@/features/allocations/types";
import { authFetch } from "@/lib/api/client";
export function TechnicianAllocations() {
  const [items, setItems] = useState<Allocation[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [error, setError] = useState("");
  useEffect(() => { const timer = window.setTimeout(async () => { try { const response = await authFetch("/api/allocations?history=true&page_size=100"); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail ?? "Allocations could not be loaded."); setItems((payload as AllocationPage).results); } catch (cause) { setError(cause instanceof Error ? cause.message : "Allocations could not be loaded."); } }, 0); return () => window.clearTimeout(timer); }, []);
  const visible = useMemo(() => items.filter((item) => (!status || item.status === status) && (!query.trim() || `${item.equipment_number} ${item.equipment_description} ${item.project_site_name} ${item.client_name}`.toLowerCase().includes(query.toLowerCase()))), [items, query, status]);
  return <div className="space-y-5 p-4 sm:p-6 lg:p-7"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-sky-700">Custody records</p><h1 className="mt-1 text-3xl font-semibold">My allocations</h1><p className="text-sm text-slate-500">Projects and equipment assigned to you, including custody history.</p></div>{error ? <p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}<Card className="border-0 ring-1 ring-slate-200"><CardHeader className="flex flex-row flex-wrap items-center justify-between gap-3"><CardTitle className="flex items-center gap-2"><ClipboardList className="size-5 text-sky-700" />Allocation records</CardTitle><div className="flex gap-2"><label className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search equipment or project…" className="w-72 pl-9" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">All statuses</option><option value="active">Active</option><option value="returned">Returned</option><option value="transferred">Transferred</option></select></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-sky-50"><tr>{["Equipment", "Description", "Category", "Brand / model", "Project / client", "Allocated", "Expected return", "Role", "Accessories", "Status"].map((item) => <th key={item} className="px-3 py-3">{item}</th>)}</tr></thead><tbody>{visible.map((item) => <tr key={item.id} className="border-b align-top"><td className="px-3 py-3 font-mono text-xs">{item.equipment_number}</td><td className="px-3 py-3 font-medium">{item.equipment_description}</td><td className="px-3 py-3">{item.equipment_category}</td><td className="px-3 py-3">{item.equipment_brand} / {item.equipment_model}</td><td className="px-3 py-3">{item.project_site_name}<span className="block text-xs text-slate-500">{item.client_name}</span></td><td className="px-3 py-3">{new Date(item.allocated_at).toLocaleString()}</td><td className="px-3 py-3">{item.expected_return ? new Date(item.expected_return).toLocaleString() : "—"}</td><td className="px-3 py-3">{item.custodian_name}<span className="block text-xs text-slate-500">Primary custodian</span></td><td className="px-3 py-3">{item.accessories.map((accessory) => `${accessory.description} ×${accessory.quantity}`).join(", ") || "None"}</td><td className="px-3 py-3"><span className={`rounded-full px-2.5 py-1 text-xs ${item.status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{item.status_name}</span></td></tr>)}</tbody></table>{!visible.length ? <p className="py-10 text-center text-sm text-slate-500">No allocations found.</p> : null}</div></CardContent></Card></div>;
}
