"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, XAxis, YAxis } from "recharts";
import { CheckCircle2, ClipboardList, Clock3, FileText, Package, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import type { Allocation, AllocationPage } from "@/features/allocations/types";
import type { ReportPage, TechnicianReport } from "@/features/reports/types";
import { authFetch } from "@/lib/api/client";
const reportColors: Record<string, string> = { draft: "#94a3b8", submitted: "#f59e0b", approved: "#10b981", rejected: "#ef4444", revision_requested: "#0ea5e9" };
const labels: Record<string, string> = { draft: "Draft", submitted: "Pending", approved: "Approved", rejected: "Rejected", revision_requested: "Revision" };
export function TechnicianDashboard() {
  const [reports, setReports] = useState<TechnicianReport[]>([]); const [allocations, setAllocations] = useState<Allocation[]>([]); const [error, setError] = useState("");
  useEffect(() => { const timer = window.setTimeout(async () => { try { const [reportResponse, allocationResponse] = await Promise.all([authFetch("/api/reports?page_size=100"), authFetch("/api/allocations?history=true&page_size=100")]); const reportPayload = await reportResponse.json(); const allocationPayload = await allocationResponse.json(); if (!reportResponse.ok || !allocationResponse.ok) throw new Error(reportPayload.detail ?? allocationPayload.detail ?? "Dashboard could not be loaded."); setReports((reportPayload as ReportPage).results); setAllocations((allocationPayload as AllocationPage).results); } catch (cause) { setError(cause instanceof Error ? cause.message : "Dashboard could not be loaded."); } }, 0); return () => window.clearTimeout(timer); }, []);
  const reportChart = useMemo(() => Object.keys(reportColors).map((status) => ({ name: labels[status], value: reports.filter((item) => item.status === status).length, color: reportColors[status] })).filter((item) => item.value), [reports]);
  const allocationChart = useMemo(() => ["active", "returned", "transferred"].map((status) => ({ name: labels[status] ?? status[0].toUpperCase() + status.slice(1), value: allocations.filter((item) => item.status === status).length })), [allocations]);
  const active = allocations.filter((item) => item.status === "active"); const overdue = active.filter((item) => item.expected_return && new Date(item.expected_return) < new Date()).length;
  const metrics = [["Reports submitted", reports.filter((item) => item.status !== "draft").length, FileText, "bg-sky-600"], ["Approved reports", reports.filter((item) => item.status === "approved").length, CheckCircle2, "bg-emerald-600"], ["Changes requested", reports.filter((item) => item.status === "revision_requested").length, RotateCcw, "bg-amber-500"], ["Active allocations", active.length, Package, "bg-violet-600"], ["Overdue returns", overdue, Clock3, "bg-rose-600"]] as const;
  return <div className="space-y-5 p-4 sm:p-6 lg:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-sky-700">Field workspace</p><h1 className="mt-1 text-3xl font-semibold">Technician dashboard</h1><p className="text-sm text-slate-500">Your report decisions and assigned equipment at a glance.</p></div><Button nativeButton={false} render={<Link href="/technician/reports" />}><FileText className="size-4" />Submit report</Button></div>{error ? <p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label, value, Icon, tone]) => <Card key={label} className="border-0 ring-1 ring-slate-200"><CardContent className="flex items-center gap-3 p-4"><span className={`flex size-11 items-center justify-center rounded-xl text-white ${tone}`}><Icon className="size-5" /></span><span><strong className="block text-2xl tabular-nums">{value}</strong><span className="text-xs text-slate-600">{label}</span></span></CardContent></Card>)}</div>
    <div className="grid gap-4 xl:grid-cols-2"><Card className="border-0 ring-1 ring-slate-200"><CardHeader><CardTitle>Report decisions</CardTitle></CardHeader><CardContent className="grid items-center gap-4 sm:grid-cols-[240px_1fr]"><ChartContainer config={{ value: { label: "Reports" } }} className="h-60 w-full" initialDimension={{ width: 240, height: 240 }}><PieChart><Pie data={reportChart} dataKey="value" nameKey="name" innerRadius={55} outerRadius={95}>{reportChart.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><ChartTooltip content={<ChartTooltipContent nameKey="name" />} /></PieChart></ChartContainer><div className="space-y-2">{reportChart.map((item) => <div key={item.name} className="flex items-center gap-2 text-sm"><span className="size-2.5 rounded-full" style={{ background: item.color }} /><span className="flex-1">{item.name}</span><strong>{item.value}</strong></div>)}</div></CardContent></Card><Card className="border-0 ring-1 ring-slate-200"><CardHeader><CardTitle>Allocation history</CardTitle></CardHeader><CardContent><ChartContainer config={{ value: { label: "Allocations" } }} className="h-60 w-full" initialDimension={{ width: 480, height: 240 }}><BarChart data={allocationChart}><CartesianGrid vertical={false} /><XAxis dataKey="name" /><YAxis allowDecimals={false} /><ChartTooltip content={<ChartTooltipContent />} /><Bar dataKey="value" fill="#0284c7" radius={[6, 6, 0, 0]} /></BarChart></ChartContainer></CardContent></Card></div>
    <Card className="border-0 ring-1 ring-slate-200"><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="flex items-center gap-2"><ClipboardList className="size-5 text-sky-700" />Current assignments</CardTitle><Button nativeButton={false} size="sm" variant="outline" render={<Link href="/technician/allocations" />}>View all</Button></CardHeader><CardContent><div className="grid gap-3 lg:grid-cols-2">{active.slice(0, 4).map((item) => <div key={item.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><p className="font-mono text-xs text-sky-700">{item.equipment_number}</p><h3 className="font-semibold">{item.equipment_description}</h3></div><span className="h-fit rounded-full bg-emerald-50 px-2.5 py-1 text-xs text-emerald-700">Active</span></div><p className="mt-3 text-sm text-slate-600">{item.project_site_name} · due {item.expected_return ? new Date(item.expected_return).toLocaleDateString() : "not set"}</p></div>)}{!active.length ? <p className="text-sm text-slate-500">No active allocations.</p> : null}</div></CardContent></Card>
  </div>;
}
